name: Build Manuals
on:
  push:
    branches: ["master"]
jobs:
  Build-Manuals:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build of main repository
        run: |
          curl \
            -X POST \
            -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/steve-fryatt/stronghelp-testing/actions/workflows/test-workflow.yml/dispatches \
            -d '{"ref":"main"}'